export interface BlogPost {
  slug: string;
  component: string;
  title: string;
  description: string;
  category: string;
  date: string;
}

export const BLOG_POSTS: BlogPost[] = [
  // Valentine & Love
  { slug: 'valentines-day-2026-india-romantic-ideas', component: 'ValentinesDay2026India', title: "Valentine's Day 2026 India: Romantic Ideas", description: "Creative and heartfelt ideas to celebrate Valentine's Day in India. From digital surprises to personalized pages.", category: 'valentine', date: '2026-05-08' },
  { slug: 'valentine-week-2026-india-calendar', component: 'ValentineWeek2026', title: 'Valentine Week 2026 India Calendar', description: 'Complete guide to Valentine Week 2026 — Rose Day to Valentine\'s Day, all 7 days explained with celebration ideas.', category: 'valentine', date: '2026-05-07' },
  { slug: 'rose-day-2026-meaning-color-guide-ideas', component: 'RoseDay2026', title: 'Rose Day 2026: Meaning, Color Guide & Ideas', description: 'Rose Day is Feb 7th — learn what each rose color means and get creative ideas for digital surprises.', category: 'valentine', date: '2026-05-08' },
  { slug: 'propose-day-2026-creative-ways-to-ask', component: 'ProposeDay2026', title: 'Propose Day 2026: Creative Ways to Ask', description: 'Feb 8th Propose Day — unique, heartfelt and creative ways to pop the question in 2026.', category: 'valentine', date: '2026-05-08' },
  { slug: 'chocolate-day-2026-romantic-ideas-india', component: 'ChocolateDay2026', title: 'Chocolate Day 2026: Romantic Ideas India', description: 'Sweeten your relationship on Chocolate Day Feb 9th with these adorable and thoughtful ideas.', category: 'valentine', date: '2026-05-08' },
  { slug: 'teddy-day-cute-messages-long-distance', component: 'TeddyDay', title: 'Teddy Day: Cute Messages for Long Distance', description: 'Make Teddy Day (Feb 10) special even from miles away with virtual hugs and personalized messages.', category: 'valentine', date: '2026-05-08' },
  { slug: 'promise-day-heartfelt-promises-couples', component: 'PromiseDay', title: 'Promise Day: Heartfelt Promises for Couples', description: 'Feb 11 Promise Day — meaningful promises to make and keep for a stronger relationship.', category: 'valentine', date: '2026-05-08' },
  { slug: 'hug-day-virtual-hugs-long-distance-india', component: 'HugDay', title: 'Hug Day: Virtual Hugs for Long Distance India', description: 'Feb 12 Hug Day ideas for couples in long distance relationships in India. Send digital warmth.', category: 'valentine', date: '2026-05-08' },
  { slug: 'kiss-day-cute-messages-couples', component: 'KissDay', title: 'Kiss Day: Cute Messages for Couples', description: 'Feb 13 Kiss Day — sweet and romantic messages to share with your partner.', category: 'valentine', date: '2026-05-08' },
  { slug: 'valentines-week-history-india-how-it-evolved', component: 'ValentineWeekHistory', title: "Valentine's Week History India: How It Evolved", description: "How Valentine's Week became a major celebration in India — history, culture and modern trends.", category: 'valentine', date: '2026-05-08' },
  // Post Valentine / Anti-Valentine
  { slug: 'slap-day-meaning-healing-after-breakup', component: 'SlapDay', title: 'Slap Day: Meaning & Healing After Breakup', description: 'Post Valentine Slap Day Feb 15 — what it means and how to use it as a day of healing and letting go.', category: 'valentine', date: '2026-05-08' },
  { slug: 'kick-day-letting-go-toxic-relationships', component: 'KickDay', title: 'Kick Day: Letting Go of Toxic Relationships', description: 'Feb 16 Kick Day — a day to finally let go of toxic people and relationships in your life.', category: 'valentine', date: '2026-05-08' },
  { slug: 'perfume-day-self-love-rituals-india', component: 'PerfumeDay', title: 'Perfume Day: Self-Love Rituals India', description: 'Feb 17 Perfume Day — self-love rituals and ways to celebrate yourself on this special day.', category: 'valentine', date: '2026-05-08' },
  { slug: 'flirt-day-rizz-quest-ideas', component: 'FlirtDay', title: 'Flirt Day: Rizz Quest Ideas', description: 'Feb 18 Flirt Day — playful ideas to add some rizz and fun to your love life.', category: 'valentine', date: '2026-05-08' },
  { slug: 'confession-day-when-and-how-to-tell-truth', component: 'ConfessionDay', title: 'Confession Day: When & How to Tell the Truth', description: 'Feb 19 Confession Day — how to express your true feelings and confess to someone special.', category: 'valentine', date: '2026-05-08' },
  { slug: 'missing-day-grief-and-letting-go', component: 'MissingDay', title: 'Missing Day: Grief & Letting Go', description: 'Feb 20 Missing Day — how to deal with missing someone and the process of letting go.', category: 'valentine', date: '2026-05-08' },
  { slug: 'breakup-day-closure-and-fresh-start', component: 'BreakupDay', title: 'Breakup Day: Closure & Fresh Start', description: 'Feb 21 Breakup Day — finding closure, healing and starting fresh after a relationship ends.', category: 'valentine', date: '2026-05-08' },
  { slug: 'gen-z-anti-valentine-tradition-india-explained', component: 'GenZAntiValentine', title: 'Gen Z Anti-Valentine Tradition India Explained', description: 'Why Gen Z in India celebrates Anti-Valentine Week and what Post Valentine means to them.', category: 'valentine', date: '2026-05-08' },
  // Friendship
  { slug: 'friendship-day-2026-wishes-messages-whatsapp', component: 'FriendshipDay2026', title: 'Friendship Day 2026: Wishes & Messages for WhatsApp', description: 'Best friendship day wishes and messages to send on WhatsApp to your best friends.', category: 'friendship', date: '2026-07-24' },
  { slug: 'friendship-day-gift-ideas-2026-india', component: 'FriendshipDayGiftIdeas', title: 'Friendship Day Gift Ideas 2026 India', description: 'Unique and affordable friendship day gift ideas for your best friends in India.', category: 'friendship', date: '2026-07-24' },
  { slug: 'friendship-day-2026-quotes-dosti-shayari-hindi-english', component: 'FriendshipDayWishes', title: 'Friendship Day 2026: Quotes, Dosti Shayari Hindi & English', description: 'Best friendship day quotes, dosti shayari in Hindi and English for your best friends.', category: 'friendship', date: '2026-07-24' },
  { slug: 'friendship-day-2026-instagram-captions-best-friend', component: 'BestFriendMessages', title: 'Friendship Day 2026: Instagram Captions for Best Friend', description: 'Perfect Instagram captions for friendship day posts with your best friend.', category: 'friendship', date: '2026-07-24' },
  { slug: 'am-i-in-love-with-my-best-friend-signs', component: 'InLoveWithBestFriend', title: 'Am I in Love with My Best Friend? Signs', description: 'How to tell if you have romantic feelings for your best friend — signs and what to do.', category: 'friendship', date: '2026-07-24' },
  { slug: 'how-to-confess-to-crush-without-ruining-friendship', component: 'ConfessToFriend', title: 'How to Confess to Crush Without Ruining Friendship', description: 'Thoughtful ways to express your feelings to your crush while keeping your friendship intact.', category: 'friendship', date: '2026-07-24' },
  { slug: 'best-friend-moving-away-farewell-messages', component: 'FriendMovingAway', title: 'Best Friend Moving Away: Farewell Messages', description: 'Heartfelt farewell messages when your best friend is moving away to a new city or country.', category: 'friendship', date: '2026-07-24' },
  // Birthday
  { slug: 'birthday-wishes-for-best-friend-50-ideas', component: 'BirthdayWishesBestFriend', title: 'Birthday Wishes for Best Friend: 50 Ideas', description: '50 heartfelt and funny birthday wishes for your best friend — from short to long, sweet to hilarious.', category: 'birthday', date: '2026-05-08' },
  { slug: 'birthday-wishes-for-girlfriend-boyfriend', component: 'BirthdayWishesGirlfriend', title: 'Birthday Wishes for Girlfriend & Boyfriend', description: 'Romantic and sweet birthday wishes for your girlfriend or boyfriend to make them feel special.', category: 'birthday', date: '2026-05-07' },
  { slug: 'birthday-wishes-for-mom-from-daughter-personalized', component: 'BirthdayWishesMom', title: 'Birthday Wishes for Mom from Daughter: Personalized', description: 'Touching and personalized birthday messages from a daughter to her beloved mother.', category: 'birthday', date: '2026-05-08' },
  { slug: 'surprise-birthday-page-ideas-pair-with-physical-gift', component: 'SurpriseBirthdayPage', title: 'Surprise Birthday Page Ideas: Pair with Physical Gift', description: 'Creative birthday surprise page ideas that work perfectly alongside a physical gift.', category: 'birthday', date: '2026-05-08' },
  { slug: '50th-birthday-milestone-message-ideas', component: 'Milestone50Birthday', title: '50th Birthday Milestone Message Ideas', description: 'Special messages and ideas to celebrate a 50th birthday — a milestone worth commemorating.', category: 'birthday', date: '2026-05-08' },
  { slug: '30th-birthday-milestone-message-ideas', component: 'Milestone30Birthday', title: '30th Birthday Milestone Message Ideas', description: 'Creative ways to celebrate and message someone on their 30th birthday milestone.', category: 'birthday', date: '2026-05-08' },
  // Relationship & Love
  { slug: 'how-to-write-love-letter-modern-couples', component: 'HowToWriteLoveLetter', title: 'How to Write a Love Letter: Modern Couples', description: "A complete guide to writing a heartfelt love letter in today's digital age.", category: 'relationship', date: '2026-05-08' },
  { slug: 'how-to-write-marriage-proposal-speech', component: 'MarriageProposalSpeech', title: 'How to Write a Marriage Proposal Speech', description: 'Step-by-step guide to crafting the perfect marriage proposal speech that will make them say yes.', category: 'relationship', date: '2026-05-08' },
  { slug: 'marriage-proposal-ideas-india', component: 'MarriageProposalIdeas', title: 'Marriage Proposal Ideas India', description: 'Creative and romantic marriage proposal ideas tailored for Indian couples.', category: 'relationship', date: '2026-05-07' },
  { slug: 'long-distance-relationship-anniversary-celebration-ideas', component: 'LongDistanceRelationship', title: 'Long Distance Relationship Anniversary Celebration Ideas', description: 'Creative ways to celebrate your anniversary when you and your partner are miles apart.', category: 'relationship', date: '2026-05-08' },
  { slug: 'long-distance-birthday-surprise-ideas-india', component: 'LongDistanceBirthday', title: 'Long Distance Birthday Surprise Ideas India', description: 'How to make your partner feel special on their birthday even when apart — India focus.', category: 'relationship', date: '2026-05-08' },
  { slug: 'how-to-say-i-miss-you-long-distance', component: 'HowToSayIMissYou', title: 'How to Say I Miss You: Long Distance', description: 'Heartfelt and creative ways to say "I miss you" to your long distance partner.', category: 'relationship', date: '2026-05-07' },
  { slug: 'how-to-make-personalized-love-page-online', component: 'MakeLovePageOnline', title: 'How to Make a Personalized Love Page Online', description: 'Step-by-step guide to creating a beautiful personalized love page online for your partner.', category: 'digital', date: '2026-05-07' },
  { slug: 'surprise-your-partner-with-a-website', component: 'SurprisePartnerWebsite', title: 'Surprise Your Partner with a Website', description: 'Why a personalized surprise website is the ultimate modern love gift for your partner.', category: 'digital', date: '2026-05-08' },
  // Girlfriend Special
  { slug: 'girlfriend-day-wishes-2026', component: 'GirlfriendDayWishes2026', title: 'Girlfriend Day Wishes 2026', description: 'Beautiful and heartfelt girlfriend day wishes and messages for 2026.', category: 'girlfriend', date: '2026-07-29' },
  { slug: 'girlfriend-day-gifts-under-500-rupees', component: 'GiftForGirlfriend', title: 'Girlfriend Day Gifts Under 500 Rupees', description: 'Thoughtful and budget-friendly girlfriend day gift ideas under ₹500.', category: 'girlfriend', date: '2026-07-30' },
  { slug: 'surprise-your-girlfriend-with-a-website', component: 'SurpriseGirlfriendWebsite', title: 'Surprise Your Girlfriend with a Website', description: 'A personalized website is the most unique and memorable gift for your girlfriend.', category: 'girlfriend', date: '2026-07-30' },
  { slug: 'website-for-my-girlfriend', component: 'WebsiteForGirlfriend', title: 'Website for My Girlfriend: Complete Guide', description: 'How to create a beautiful personalized website for your girlfriend as a surprise gift.', category: 'girlfriend', date: '2026-07-29' },
  { slug: 'cute-website-for-my-girlfriend', component: 'CuteWebsiteGirlfriend', title: 'Cute Website for My Girlfriend: Ideas', description: 'Adorable and cute website ideas to create for your girlfriend as a digital love gift.', category: 'girlfriend', date: '2026-07-29' },
  { slug: 'romantic-website-ideas-for-girlfriend', component: 'RomanticWebsiteGirlfriend', title: 'Romantic Website Ideas for Girlfriend', description: 'Romantic and beautiful website ideas to surprise your girlfriend and make her feel loved.', category: 'girlfriend', date: '2026-07-30' },
  { slug: 'when-is-girlfriend-day-2026', component: 'NationalGirlfriendDay', title: 'When is Girlfriend Day 2026?', description: 'Complete guide to National Girlfriend Day 2026 — date, history and celebration ideas.', category: 'girlfriend', date: '2026-07-29' },
  // Couples
  { slug: 'couples-day-2026-india', component: 'CouplesDay2026', title: "Couples Day 2026 India", description: "Complete guide to National Couples Day 2026 in India — date, ideas and how to celebrate.", category: 'couples', date: '2026-08-08' },
  { slug: 'couples-day-gift-ideas-2026', component: 'CoupleDayGiftIdeas', title: 'Couples Day Gift Ideas 2026', description: 'Best couples day gift ideas for 2026 — from digital surprises to unique experiences.', category: 'couples', date: '2026-08-09' },
  { slug: 'when-is-couples-day-2026', component: 'WhenIsCouplesDay', title: 'When is Couples Day 2026?', description: 'When is National Couples Day 2026? Date, history and everything you need to know.', category: 'couples', date: '2026-08-08' },
  // Anniversary
  { slug: 'first-anniversary-personalized-page-ideas', component: 'FirstAnniversary', title: 'First Anniversary Personalized Page Ideas', description: 'Make your first anniversary unforgettable with these personalized page and gift ideas.', category: 'anniversary', date: '2026-05-08' },
  { slug: '5-year-anniversary-memory-book-ideas', component: 'Anniversary5Year', title: '5 Year Anniversary Memory Book Ideas', description: 'Beautiful ideas for a 5th year anniversary memory book — digital and physical options.', category: 'anniversary', date: '2026-05-08' },
  { slug: '25-year-silver-anniversary-personalized-tribute', component: 'Anniversary25Year', title: '25 Year Silver Anniversary Personalized Tribute', description: 'Create a stunning silver anniversary tribute for 25 years of love and togetherness.', category: 'anniversary', date: '2026-05-08' },
  // Apology
  { slug: 'how-to-apologize-sincerely', component: 'HowToApologize', title: 'How to Apologize Sincerely', description: 'A heartfelt guide to making a genuine apology that heals relationships and rebuilds trust.', category: 'apology', date: '2026-05-07' },
  { slug: 'how-to-write-apology-letter-to-girlfriend', component: 'ApologyLetterGirlfriend', title: 'How to Write an Apology Letter to Girlfriend', description: 'Step-by-step guide to writing a sincere and effective apology letter to your girlfriend.', category: 'apology', date: '2026-05-08' },
  { slug: 'how-to-apologize-to-best-friend-after-fight', component: 'ApologyAfterFight', title: 'How to Apologize to Best Friend After Fight', description: 'Practical tips and message templates to repair your friendship after an argument.', category: 'apology', date: '2026-05-08' },
  // Digital & How-To
  { slug: 'how-to-make-a-couple-website', component: 'MakePersonalizedWebsite', title: 'How to Make a Couple Website', description: 'Complete guide to creating a beautiful couple website to celebrate your love story.', category: 'digital', date: '2026-05-08' },
  { slug: 'cost-to-make-couple-website', component: 'CostOfCoupleWebsite', title: 'Cost to Make a Couple Website', description: 'How much does it cost to make a personalized couple website? Complete pricing guide.', category: 'digital', date: '2026-05-08' },
  { slug: 'best-romantic-website-builders-2026-comparison', component: 'BestRomanticWebsiteBuilders', title: 'Best Romantic Website Builders 2026: Comparison', description: 'Compare the best platforms for creating romantic personalized websites in 2026.', category: 'digital', date: '2026-05-08' },
  { slug: 'digital-vs-physical-gifting-india-2026-trends', component: 'DigitalVsPhysicalGifting', title: 'Digital vs Physical Gifting India 2026 Trends', description: 'How India is shifting from physical to digital gifting — trends and insights for 2026.', category: 'digital', date: '2026-05-08' },
  { slug: 'why-young-indians-prefer-digital-greetings-data', component: 'WhyYoungIndiansDigital', title: 'Why Young Indians Prefer Digital Greetings: Data', description: 'Data-driven insights into why millennials and Gen Z in India love digital greeting cards.', category: 'digital', date: '2026-05-08' },
  { slug: 'earn-money-selling-website-templates-india-2026', component: 'EarnMoneySelling', title: 'Earn Money Selling Website Templates India 2026', description: 'How to earn money by selling personalized website templates in India in 2026.', category: 'digital', date: '2026-07-24' },
  // Indian Occasions
  { slug: 'raksha-bandhan-2026-wishes-messages-sister-brother', component: 'RakshaBandhan2026', title: 'Raksha Bandhan 2026: Wishes & Messages Sister Brother', description: 'Heartfelt Raksha Bandhan 2026 wishes and messages for sisters and brothers.', category: 'indian', date: '2026-07-24' },
  { slug: 'diwali-2026-digital-companion-physical-gift', component: 'Diwali2026', title: 'Diwali 2026: Digital Companion to Physical Gift', description: 'Make Diwali 2026 extra special with a personalized digital companion alongside your physical gift.', category: 'indian', date: '2026-05-08' },
  { slug: 'holi-2026-colorful-page-for-loved-ones-abroad', component: 'Holi2026', title: 'Holi 2026: Colorful Page for Loved Ones Abroad', description: 'Send the colors of Holi to your loved ones abroad with a personalized digital greeting page.', category: 'indian', date: '2026-05-08' },
  { slug: 'eid-mubarak-2026-personalized-page-ideas', component: 'Eid2026', title: 'Eid Mubarak 2026: Personalized Page Ideas', description: 'Beautiful personalized Eid Mubarak page ideas to share joy with your loved ones.', category: 'indian', date: '2026-05-08' },
  { slug: 'mothers-day-india-2026-personalized-tribute', component: 'MothersDay2026', title: "Mother's Day India 2026: Personalized Tribute", description: "Create a beautiful personalized tribute for your mother on Mother's Day 2026.", category: 'indian', date: '2026-05-08' },
  { slug: 'fathers-day-india-2026-personalized-tribute', component: 'FathersDay2026', title: "Father's Day India 2026: Personalized Tribute", description: "Honor your father with a personalized tribute page on Father's Day 2026.", category: 'indian', date: '2026-05-08' },
  { slug: 'teachers-day-2026-thank-you-messages-india', component: 'TeachersDay2026', title: "Teacher's Day 2026: Thank You Messages India", description: "Heartfelt thank you messages for teachers on Teacher's Day 2026 in India.", category: 'indian', date: '2026-07-24' },
];
